### PR TITLE
Fix reconcile always refresh service nodeport number

### LINKED ISSUE #541: [Bug] MariaDB Galera Service constantly refreshing NodePort port number
**Describe the bug**
I encountered an issue with the MariaDB Galera Service where the NodePort assigned to the service keeps refreshing the port number. This behavior is causing inconsistency and disruption in accessing the MariaDB Galera cluster.

image

after seconds...
image
<!--

```

**Expected behaviour**
<!--A concise description of what you expected to happen.-->

**Steps to reproduce the bug**
<!--Steps to reproduce the bug should be clear and easily reproducible to help people
gain an understanding of the problem.-->

1. Create a galera cluster
2. kubectl get svc


**Environment details**:
- Kubernetes version: v1.17.2
- mariadb-operator version: 0.0.27
- Install method: helm
- Install flavor: custom

**Additional context**
<!--Add any other context  here.-->

### PR DESCRIPTION
**Pull request by luohaha3123**
Closes #541 
This PR aims to fix the k8s controller refreshing of the service NodePort. The NodePort was being refreshed constantly, causing instability and disruption in the service availability.

### CODE REVIEW

**Comment by luohaha3123** [comment]
@mmontes11

File: pkg/controller/service/controller.go [hunk 1]
```diff
@@ -53,3 +53,34 @@ func (r *ServiceReconciler) Reconcile(ctx context.Context, desiredSvc *corev1.Se
...
+		existingPorts[port.Port] = true
+	}
+
+	for _, desiredPort := range desiredSvc.Spec.Ports {
+		if !existingPorts[desiredPort.Port] {
+			existingSvc.Spec.Ports = append(existingSvc.Spec.Ports, desiredPort)
+		}
+	}
+
+	if desiredSvc.Spec.Type != corev1.ServiceTypeNodePort {
```
Comment (mmontes11) [inline pkg/controller/service/controller.go:81]:
```suggestion
	if desiredSvc.Spec.Type != corev1.ServiceTypeNodePort &&
		desiredSvc.Spec.Type != corev1.ServiceTypeLoadBalancer {
		for i := range existingSvc.Spec.Ports {
			existingSvc.Spec.Ports[i].NodePort = 0
		}
	}
```

I would not cleanup the `nodePort` when the `Service` type is `LoadBalancer`, as its connectivity model relies on the `nodePort` being present i.e. the cloud load balancer connects to the Kubernetes node in that port

**Review by mmontes11 — CHANGES_REQUESTED** [review]
Hey there @luohaha3123 ! Thanks a lot for your contribution, very much appreciated  🦭 🙇🏻 

Left a comment regarding `LoadBalancer` service types! Other than that LGTM! 

Tests very much appreciated 🙏🏻

File: pkg/controller/service/controller.go (hunk 1 above)
Comment (luohaha3123) [reply pkg/controller/service/controller.go]: @mmontes11 Thanks for your suggestion, I have to add **LoadBalancer** type in **updateServicePorts**, please review again!

**Review by mmontes11 — APPROVED** [review]
LGTM! 👍🏻 

Thanks a lot for your contribution @luohaha3123 🦭 🙇🏻
