### PR TITLE
Embed PodTemplate in the Exporter struct

### LINKED ISSUE #348: [Bug]  No `podSecurityContext` on metrics deployments
**Documentation**

- [x] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**

In 0.0.24 the metrics exporter was moved from a sidecar to a stand-alone deployment.
The stand-alone deployment doesn't have a `podSecurityContext` set, this means it can't be deployed in namespaces with enforced restrictive pod-security labels.

**Expected behaviour**

The metrics exporter should use the `podSecurityContext` set on the spec of the `MariaDB` object.
(Or a separate `podSecurityContext` can be set for the metrics exporter)

**Steps to reproduce the bug**

Create a MariaDB resource with:

```
metrics: 
  enabled: true
```

in a namespace with a restrictive PSS set with the labels:

```
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
```

**Debug information**

No `podSecurityContext` is being configured on the deployed here: https://github.com/mariadb-operator/mariadb-operator/blob/v0.0.24/pkg/builder/deployment_buider.go#L41-68

**Environment details**:
- Kubernetes version: 1.26
- Kubernetes distribution: EKS
- mariadb-operator version: 0.0.24
- Install method: static manifests
- Install flavor: custom

**Additional context**

### PR DESCRIPTION
**Pull request by gg-kialo**
This allows configuring the properties like `podSecurityContext` and `nodeSelector` on the metrics exporter.

Fixes #348

### CODE REVIEW

File: pkg/builder/deployment_builder.go [hunk 1]
```diff
@@ -23,6 +23,39 @@ const (
...
+						},
+					},
+				},
+			},
+			SecurityContext:           mariadb.Spec.Metrics.Exporter.PodSecurityContext,
+			Affinity:                  mariadb.Spec.Metrics.Exporter.Affinity,
+			NodeSelector:              mariadb.Spec.Metrics.Exporter.NodeSelector,
+			Tolerations:               mariadb.Spec.Metrics.Exporter.Tolerations,
+			PriorityClassName:         priorityClass(mariadb.Spec.Metrics.Exporter.PriorityClassName),
+			TopologySpreadConstraints: mariadb.Spec.Metrics.Exporter.TopologySpreadConstraints,
```
Comment (gg-kialo) [inline pkg/builder/deployment_builder.go:54]: I added the fields that I thought would be useful here. I'm only setting `securityContext` and `nodeSelector` myself.

Comment (mmontes11) [reply pkg/builder/deployment_builder.go:54]: Fantastic! Sounds reasonable to me as well.
